os:
  - linux
dist: focal

language: python
python:
  - "3.11"

install:
  - pip install -r requirements.txt

stages:
- test

jobs:
  include:
    - stage: test
      name: "test"
      script:
        - python3 -m unittest
